
# params
baseURL = 'https://sinyks.github.io/'
languageCode = 'ch-fr'
title = "It's dangerous to go alone"
theme = 'smol'

[params]
#    subtitle = "Yet another tech blog"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

#  [[menu.main]]
#        identifier = "categories"
#        name = "Categories"
#        url = "/categories/"
#        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2 

# Footer
